/usr/local/python27/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

/home/pirate/optools/zabbix/web/urls.py:32: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^disable_trigger/',views.change_trigger_status),

/home/pirate/optools/zabbix/web01/urls.py:28: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^tree/(\d.+)*/(\d+)*',views.tree),

/home/pirate/optools/zabbix/zabbix/urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^web01/',include('web01.urls')),

[25/Oct/2018 02:10:52] "GET /web/zhanshi/available/2/ HTTP/1.1" 200 31168
[25/Oct/2018 02:10:55] "GET /web/zhanshi/status/1/ HTTP/1.1" 200 84676
[25/Oct/2018 02:11:00] "GET /web/mass_addhost/ HTTP/1.1" 200 13058
[25/Oct/2018 02:11:01] "GET /web/deletehost/ HTTP/1.1" 200 9138
[25/Oct/2018 02:11:02] "GET /web/update_hostid/ HTTP/1.1" 200 9308
[25/Oct/2018 02:11:05] "GET /web/disable_trigger HTTP/1.1" 301 0
[25/Oct/2018 02:11:05] "GET /web/disable_trigger/ HTTP/1.1" 200 9439
Not Found: /web01/disable_trigger/
[25/Oct/2018 02:11:07] "GET /web01/disable_trigger/ HTTP/1.1" 404 4530
Not Found: /favicon.ico
[25/Oct/2018 02:11:07] "GET /favicon.ico HTTP/1.1" 404 2263
[25/Oct/2018 02:11:12] "GET /web/zabbixlosthostlist/ HTTP/1.1" 200 13404
[25/Oct/2018 02:11:16] "GET /web/zabbixlosthostlist/2 HTTP/1.1" 200 13404
[25/Oct/2018 02:11:17] "GET /web/zabbixlosthostlist/3 HTTP/1.1" 200 13404
[25/Oct/2018 02:11:17] "GET /web/zabbixlosthostlist/4 HTTP/1.1" 200 12594
[25/Oct/2018 02:11:24] "GET /web/zabbixlosthostlist/1 HTTP/1.1" 200 13404
[25/Oct/2018 02:11:25] "GET /web/zabbixlosthostlist/2 HTTP/1.1" 200 13404
[25/Oct/2018 02:11:26] "GET /web/zabbixlosthostlist/3 HTTP/1.1" 200 13404
[25/Oct/2018 02:11:26] "GET /web/zabbixlosthostlist/4 HTTP/1.1" 200 12594
[25/Oct/2018 02:11:29] "GET /web/zabbix_deletelist/2 HTTP/1.1" 301 0
[25/Oct/2018 02:11:29] "GET /web/zabbix_deletelist/2/ HTTP/1.1" 200 16358
[25/Oct/2018 02:11:35] "GET /web/zabbix_deletelist/2/ HTTP/1.1" 200 16358
[25/Oct/2018 02:11:38] "GET /web/zabbix_deletelist/3 HTTP/1.1" 301 0
[25/Oct/2018 02:11:38] "GET /web/zabbix_deletelist/3/ HTTP/1.1" 200 13790
[25/Oct/2018 02:11:43] "GET /web/dashboard/ HTTP/1.1" 200 11467
[25/Oct/2018 02:11:56] "GET /web/update_hostid/ HTTP/1.1" 200 9308
[25/Oct/2018 02:11:58] "GET /web/deletehost/ HTTP/1.1" 200 9138
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.
October 25, 2018 - 02:10:37
Django version 1.9.7, using settings 'zabbix.settings'
Starting development server at http://192.168.2.199:8000/
Quit the server with CONTROL-C.
{u'user': u'hantao'}
===============
xxx f21016063bec10a77e97d8c4300c5322
{u'user': u'hantao'}
===============
xxx 47df76e6e23d5c85d34853db201bf81a
{u'user': u'hantao'}
===============
{u'user': u'hantao'}
===============
{u'user': u'hantao'}
===============
{u'user': u'hantao'}
===============
/home/pirate/optools/zabbix/list//create.list
{u'user': u'hantao'}
===============
/home/pirate/optools/zabbix/list//create.list
{u'user': u'hantao'}
===============
/home/pirate/optools/zabbix/list//create.list
{u'user': u'hantao'}
===============
/home/pirate/optools/zabbix/list//create.list
{u'user': u'hantao'}
===============
/home/pirate/optools/zabbix/list//create.list
{u'user': u'hantao'}
===============
/home/pirate/optools/zabbix/list//create.list
{u'user': u'hantao'}
===============
/home/pirate/optools/zabbix/list//create.list
{u'user': u'hantao'}
===============
/home/pirate/optools/zabbix/list//create.list
{u'user': u'hantao'}
===============
{u'user': u'hantao'}
===============
{u'user': u'hantao'}
===============
{u'user': u'hantao'}
===============
xxx 965790be80868eaf7c49f9dc6fb9d820
{'1': 250, '0': 163, '2': 13}
{u'user': u'hantao'}
===============
{u'user': u'hantao'}
===============
/usr/local/python27/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

/home/pirate/optools/zabbix/web/urls.py:32: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^disable_trigger/',views.change_trigger_status),

/home/pirate/optools/zabbix/web01/urls.py:28: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^tree/(\d.+)*/(\d+)*',views.tree),

/home/pirate/optools/zabbix/zabbix/urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^web01/',include('web01.urls')),

/usr/local/python27/lib/python2.7/site-packages/django/template/defaulttags.py:67: UserWarning: A {% csrf_token %} was used in a template, but the context did not provide the value.  This is usually caused by not using RequestContext.
  "A {% csrf_token %} was used in a template, but the context "

[27/Oct/2018 13:47:39] "GET /web/zhanshi/available/0/ HTTP/1.1" 200 2467
[27/Oct/2018 13:47:40] "GET /static/signin.css HTTP/1.1" 200 793
[27/Oct/2018 13:47:40] "GET /static/favicon.ico HTTP/1.1" 200 32988
[27/Oct/2018 13:47:42] "POST /web/login/ HTTP/1.1" 200 11536
[27/Oct/2018 13:47:43] "GET /web/mass_addhost/ HTTP/1.1" 200 13058
/usr/local/python27/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

/home/pirate/optools/zabbix/web/urls.py:32: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^disable_trigger/',views.change_trigger_status),

/home/pirate/optools/zabbix/web01/urls.py:28: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^tree/(\d.+)*/(\d+)*',views.tree),

/home/pirate/optools/zabbix/zabbix/urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^web01/',include('web01.urls')),

Error: That port is already in use.
*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Oct 28 12:27:15 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 28 October 2018 01:51:20
os: Linux-3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015
nodename: hantao-2-199
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 24
current working directory: /home/pirate/optools/zabbix
detected binary path: /usr/local/python27/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 65536
building mime-types dictionary from file /etc/mime.types...883 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
spawned uWSGI http 1 (pid: 3482)
uwsgi socket 0 bound to TCP address 127.0.0.1:34044 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.3 (default, Sep 11 2017, 13:46:59)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9ef500
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "zabbix/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/usr/local/python27/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/python27/lib/python2.7/site-packages/django/utils/module_loading.py", line 43, in autodiscover_modules
    for app_config in apps.get_app_configs():
  File "/usr/local/python27/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/python27/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 3481, cores: 1)
*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Oct 28 12:29:49 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 28 October 2018 01:51:20
os: Linux-3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015
nodename: hantao-2-199
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 24
current working directory: /home/pirate/optools/zabbix
detected binary path: /usr/local/python27/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 65536
building mime-types dictionary from file /etc/mime.types...883 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 192.168.2.199:8000 fd 4
spawned uWSGI http 1 (pid: 3508)
uwsgi socket 0 bound to TCP address 127.0.0.1:58428 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.3 (default, Sep 11 2017, 13:46:59)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xd2f500
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "zabbix/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/usr/local/python27/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/python27/lib/python2.7/site-packages/django/utils/module_loading.py", line 43, in autodiscover_modules
    for app_config in apps.get_app_configs():
  File "/usr/local/python27/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/python27/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 3507, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 3507|app: -1|req: -1/1] 192.168.2.50 () {38 vars in 682 bytes} [Sun Oct 28 12:30:01 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 3507|app: -1|req: -1/2] 192.168.2.50 () {38 vars in 665 bytes} [Sun Oct 28 12:30:02 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 3507|app: -1|req: -1/3] 192.168.2.50 () {38 vars in 730 bytes} [Sun Oct 28 12:30:06 2018] GET /web/zhanshi/available/0/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 3507|app: -1|req: -1/4] 192.168.2.50 () {38 vars in 689 bytes} [Sun Oct 28 12:30:07 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 3507|app: -1|req: -1/5] 192.168.2.50 () {40 vars in 761 bytes} [Sun Oct 28 12:30:20 2018] GET /web/zhanshi/available/0/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 3507|app: -1|req: -1/6] 192.168.2.50 () {38 vars in 689 bytes} [Sun Oct 28 12:30:20 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Oct 28 12:34:25 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 28 October 2018 01:51:20
os: Linux-3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015
nodename: hantao-2-199
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 24
current working directory: /home/pirate/optools/zabbix
detected binary path: /usr/local/python27/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 65536
building mime-types dictionary from file /etc/mime.types...883 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 192.168.2.199:8000 fd 4
spawned uWSGI http 1 (pid: 3520)
uwsgi socket 0 bound to TCP address 127.0.0.1:58610 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.3 (default, Sep 11 2017, 13:46:59)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x195c500
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x195c500 pid: 3519 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 3519, cores: 1)
/usr/local/python27/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

./web/urls.py:32: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^disable_trigger/',views.change_trigger_status),

./web01/urls.py:28: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^tree/(\d.+)*/(\d+)*',views.tree),

./zabbix/urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^web01/',include('web01.urls')),

{u'user': u'hantao'}
===============
xxx bd317ff11172af4b359a2466de4a2a87
[pid: 3519|app: 0|req: 1/1] 192.168.2.50 () {40 vars in 761 bytes} [Sun Oct 28 04:34:33 2018] GET /web/zhanshi/available/0/ => generated 84902 bytes in 1502 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
[pid: 3519|app: 0|req: 2/2] 192.168.2.50 () {40 vars in 784 bytes} [Sun Oct 28 04:34:38 2018] GET /web/update_hostid/ => generated 9308 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 23444f0e634756972160c002ef66cc9a
[pid: 3519|app: 0|req: 3/3] 192.168.2.50 () {40 vars in 790 bytes} [Sun Oct 28 04:34:39 2018] GET /web/zhanshi/available/2/ => generated 29671 bytes in 949 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
[pid: 3519|app: 0|req: 4/4] 192.168.2.50 () {40 vars in 776 bytes} [Sun Oct 28 04:34:40 2018] GET /web/mass_addhost/ => generated 13460 bytes in 11 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Oct 28 12:38:16 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 28 October 2018 01:51:20
os: Linux-3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015
nodename: hantao-2-199
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 24
current working directory: /home/pirate/optools/zabbix
detected binary path: /usr/local/python27/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 65536
building mime-types dictionary from file /etc/mime.types...883 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
spawned uWSGI http 1 (pid: 3537)
uwsgi socket 0 bound to TCP address 127.0.0.1:52405 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.3 (default, Sep 11 2017, 13:46:59)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x241c500
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x241c500 pid: 3536 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 3536, cores: 1)
*** Starting uWSGI 2.0.17.1 (64bit) on [Sun Oct 28 12:41:46 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 28 October 2018 01:51:20
os: Linux-3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015
nodename: hantao-2-199
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 24
current working directory: /home/pirate/optools/zabbix
detected binary path: /usr/local/python27/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 65536
building mime-types dictionary from file /etc/mime.types...883 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 192.168.2.199:8000 fd 4
spawned uWSGI http 1 (pid: 3555)
uwsgi socket 0 bound to TCP address 127.0.0.1:55729 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.3 (default, Sep 11 2017, 13:46:59)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1c38500
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1c38500 pid: 3554 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 3554, cores: 1)
/usr/local/python27/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

./web/urls.py:32: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^disable_trigger/',views.change_trigger_status),

./web01/urls.py:28: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^tree/(\d.+)*/(\d+)*',views.tree),

./zabbix/urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^web01/',include('web01.urls')),

Not Found: /
[pid: 3554|app: 0|req: 1/1] 192.168.2.50 () {38 vars in 682 bytes} [Sun Oct 28 04:42:37 2018] GET / => generated 2230 bytes in 74 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 3554|app: 0|req: 2/2] 192.168.2.50 () {38 vars in 665 bytes} [Sun Oct 28 04:42:38 2018] GET /favicon.ico => generated 2263 bytes in 4 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 4582ec7a4c48065d20b81e6b7f180970
[pid: 3554|app: 0|req: 3/3] 192.168.2.50 () {38 vars in 730 bytes} [Sun Oct 28 05:49:42 2018] GET /web/zhanshi/available/0/ => generated 84902 bytes in 1349 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 3554|app: 0|req: 4/4] 192.168.2.50 () {38 vars in 682 bytes} [Sun Oct 28 05:53:20 2018] GET / => generated 2230 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /
[pid: 3554|app: 0|req: 5/5] 192.168.2.50 () {38 vars in 682 bytes} [Sun Oct 28 05:59:53 2018] GET / => generated 2230 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 3554|app: 0|req: 6/6] 192.168.2.50 () {38 vars in 665 bytes} [Sun Oct 28 05:59:54 2018] GET /favicon.ico => generated 2263 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 4c129d098685a9731f0d4d20d4d068d6
[pid: 3554|app: 0|req: 7/7] 192.168.2.50 () {38 vars in 730 bytes} [Sun Oct 28 06:00:10 2018] GET /web/zhanshi/available/0/ => generated 84902 bytes in 938 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 4b4a08ee754ecab5c91d41001daa8980
[pid: 3554|app: 0|req: 8/8] 192.168.2.50 () {40 vars in 796 bytes} [Sun Oct 28 06:00:51 2018] GET /web/zhanshi/available/2/ => generated 29671 bytes in 1072 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 61ad3d28c67de5d02481d7866babeab2
[pid: 3554|app: 0|req: 9/9] 192.168.2.50 () {40 vars in 790 bytes} [Sun Oct 28 06:00:54 2018] GET /web/zhanshi/status/1/ => generated 84676 bytes in 1155 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 59f74497a2be6d1d9b17f491c215ec1d
[pid: 3554|app: 0|req: 10/10] 192.168.2.50 () {40 vars in 793 bytes} [Sun Oct 28 06:00:59 2018] GET /web/zhanshi/available/2/ => generated 29671 bytes in 1107 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx f12c9a088c535cb074aa6a22c839492c
[pid: 3554|app: 0|req: 11/11] 192.168.2.50 () {40 vars in 796 bytes} [Sun Oct 28 06:01:04 2018] GET /web/zhanshi/available/2/ => generated 29671 bytes in 1134 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 3554|app: 0|req: 12/12] 192.168.2.50 () {40 vars in 912 bytes} [Sun Oct 28 06:01:08 2018] GET /web/edit/yz-hhw-apple-mdb-9-218-008/10474/192.168.9.218/%E5%AE%95%E6%9C%BA%E7%8A%B6%E6%80%81/1 => generated 0 bytes in 4 msecs (HTTP/1.1 301) 3 headers in 211 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 7c08d2ccc587529e9f082b07d8524aff
ret {'username': u'hantao', 'ip': u'192.168.9.218', 'hostname': u'yz-hhw-apple-mdb-9-218-008', 'hostid': u'10474', 'status_name': u'\u5b95\u673a\u72b6\u6001'}
<type 'dict'>
[pid: 3554|app: 0|req: 13/13] 192.168.2.50 () {40 vars in 914 bytes} [Sun Oct 28 06:01:08 2018] GET /web/edit/yz-hhw-apple-mdb-9-218-008/10474/192.168.9.218/%E5%AE%95%E6%9C%BA%E7%8A%B6%E6%80%81/1/ => generated 9567 bytes in 125 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 19cfe3887329a97030dc52af52f30870
[pid: 3554|app: 0|req: 14/14] 192.168.2.50 () {40 vars in 867 bytes} [Sun Oct 28 06:01:14 2018] GET /web/zhanshi/available/2/ => generated 29671 bytes in 1296 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
[pid: 3554|app: 0|req: 15/15] 192.168.2.50 () {40 vars in 782 bytes} [Sun Oct 28 06:01:16 2018] GET /web/mass_addhost/ => generated 13460 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
[pid: 3554|app: 0|req: 16/16] 192.168.2.50 () {40 vars in 747 bytes} [Sun Oct 28 06:13:54 2018] GET /web/mass_addhost/ => generated 13460 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
[pid: 3554|app: 0|req: 17/17] 192.168.2.50 () {40 vars in 775 bytes} [Sun Oct 28 06:14:02 2018] GET /web/mass_addhost/ => generated 13460 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 3554|app: 0|req: 18/18] 192.168.2.50 () {40 vars in 781 bytes} [Sun Oct 28 06:14:06 2018] GET /web/disable_trigger/ => generated 9439 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
[pid: 3554|app: 0|req: 19/19] 192.168.2.50 () {40 vars in 780 bytes} [Sun Oct 28 06:14:09 2018] GET /web/update_hostid/ => generated 9308 bytes in 13 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 3554|app: 0|req: 20/20] 192.168.2.50 () {40 vars in 782 bytes} [Sun Oct 28 06:14:18 2018] GET /web/disable_trigger/ => generated 9439 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx c7394f0c21c7560f95a78c42155e0730
[pid: 3554|app: 0|req: 21/21] 192.168.2.50 () {40 vars in 792 bytes} [Sun Oct 28 06:14:20 2018] GET /web/zhanshi/available/2/ => generated 29671 bytes in 1081 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx cf06ca157a7ed35a6d9dd9b7a6bd4661
[pid: 3554|app: 0|req: 22/22] 192.168.2.50 () {38 vars in 730 bytes} [Sun Oct 28 06:17:36 2018] GET /web/zhanshi/available/0/ => generated 84902 bytes in 1143 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 81bd7bf202a034be070e10154dbba34d
[pid: 3554|app: 0|req: 23/23] 192.168.2.50 () {38 vars in 728 bytes} [Sun Oct 28 06:33:55 2018] GET /web/zhanshi/available/0/ => generated 84902 bytes in 1257 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
None
/usr/local/python27/lib/python2.7/site-packages/django/template/defaulttags.py:67: UserWarning: A {% csrf_token %} was used in a template, but the context did not provide the value.  This is usually caused by not using RequestContext.
  "A {% csrf_token %} was used in a template, but the context "

[pid: 3554|app: 0|req: 24/24] 192.168.164.4 () {36 vars in 674 bytes} [Tue Oct 30 03:56:37 2018] GET /web/zhanshi/available/0/ => generated 2467 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 3554|app: -1|req: -1/25] 192.168.164.4 () {36 vars in 624 bytes} [Tue Oct 30 03:56:37 2018] GET /static/signin.css => generated 793 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 3 headers in 110 bytes (0 switches on core 0)
[pid: 3554|app: 0|req: 25/26] 192.168.164.4 () {46 vars in 853 bytes} [Tue Oct 30 03:56:38 2018] POST /web/login/ => generated 11536 bytes in 350 msecs (HTTP/1.1 200) 4 headers in 233 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
[pid: 3554|app: 0|req: 26/27] 192.168.164.4 () {40 vars in 765 bytes} [Tue Oct 30 03:56:43 2018] GET /web/deletehost/ => generated 9138 bytes in 11 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
12160
<type 'str'>
10474
<type 'str'>
11833
<type 'str'>
[pid: 3554|app: 0|req: 27/28] 192.168.164.4 () {48 vars in 911 bytes} [Tue Oct 30 03:56:46 2018] POST /web/deletehost/ => generated 9155 bytes in 3547 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
/home/pirate/optools/zabbix/list//create.list
[pid: 3554|app: 0|req: 28/29] 192.168.164.4 () {40 vars in 786 bytes} [Wed Oct 31 06:40:42 2018] GET /web/zabbixlosthostlist/ => generated 13404 bytes in 100 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
/home/pirate/optools/zabbix/list//create.list
[pid: 3554|app: 0|req: 29/30] 192.168.164.4 () {40 vars in 796 bytes} [Wed Oct 31 06:40:43 2018] GET /web/zabbixlosthostlist/4 => generated 13577 bytes in 68 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 9f92fa371cb7fbe79d0909cb72644c50
[pid: 3554|app: 0|req: 30/31] 192.168.164.4 () {40 vars in 797 bytes} [Thu Nov  1 01:48:49 2018] GET /web/zhanshi/available/2/ => generated 23387 bytes in 1097 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx c6789cc445581271ab8b47267a231565
[pid: 3554|app: 0|req: 31/32] 192.168.164.4 () {40 vars in 797 bytes} [Thu Nov  1 01:48:53 2018] GET /web/zhanshi/available/2/ => generated 23387 bytes in 952 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 7b01a7c66d18d88715de9829c426713d
[pid: 3554|app: 0|req: 32/33] 192.168.164.4 () {40 vars in 791 bytes} [Thu Nov  1 02:47:43 2018] GET /web/zhanshi/status/1/ => generated 84693 bytes in 1289 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 3554|app: -1|req: -1/34] 192.168.164.4 () {38 vars in 701 bytes} [Thu Nov  1 02:47:45 2018] GET /static/favicon.ico => generated 32988 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 3 headers in 128 bytes (0 switches on core 0)
{u'user': u'hantao'}
===============
xxx 54b5444921e151edb55036fb193cb9ec
[pid: 3554|app: 0|req: 33/35] 192.168.164.4 () {40 vars in 794 bytes} [Thu Nov  1 10:40:22 2018] GET /web/zhanshi/available/2/ => generated 26422 bytes in 1200 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx dc1f20437231ce92453b5cbfa5ab1c59
[pid: 3554|app: 0|req: 34/36] 192.168.164.4 () {38 vars in 731 bytes} [Fri Nov  2 01:54:19 2018] GET /web/zhanshi/available/0/ => generated 84901 bytes in 1494 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 3554|app: 0|req: 35/37] 192.168.164.4 () {40 vars in 787 bytes} [Fri Nov  2 01:54:27 2018] GET /web/disable_trigger => generated 0 bytes in 1 msecs (HTTP/1.1 301) 3 headers in 136 bytes (1 switches on core 0)
[pid: 3554|app: 0|req: 36/38] 192.168.164.4 () {40 vars in 789 bytes} [Fri Nov  2 01:54:27 2018] GET /web/disable_trigger/ => generated 9439 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
[pid: 3554|app: 0|req: 37/39] 192.168.164.4 () {40 vars in 781 bytes} [Fri Nov  2 01:54:28 2018] GET /web/update_hostid/ => generated 9308 bytes in 11 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
female
Internal Server Error: /web/update_hostid/
Traceback (most recent call last):
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./web/views.py", line 38, in war
    return  fun(request,*arg,**kwargs)
  File "./web/views.py", line 401, in update_hostid
    p.update_hoststatus(ip,genber)
  File "./web/zabbix_api.py", line 118, in update_hoststatus
    result = result[0]
IndexError: list index out of range
[pid: 3554|app: 0|req: 38/40] 192.168.164.4 () {48 vars in 920 bytes} [Fri Nov  2 01:54:34 2018] POST /web/update_hostid/ => generated 66299 bytes in 223 msecs (HTTP/1.1 500) 3 headers in 106 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 3554|app: 0|req: 39/41] 192.168.164.4 () {38 vars in 684 bytes} [Fri Nov  2 01:54:35 2018] GET /favicon.ico => generated 2263 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
female
[pid: 3554|app: 0|req: 40/42] 192.168.164.4 () {48 vars in 920 bytes} [Fri Nov  2 01:54:50 2018] POST /web/update_hostid/ => generated 9331 bytes in 2873 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 4db5d624cb7f6e24fc0955c536309707
[pid: 3554|app: 0|req: 41/43] 192.168.164.4 () {40 vars in 791 bytes} [Fri Nov  2 09:50:50 2018] GET /web/zhanshi/available/2/ => generated 26393 bytes in 1204 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 97bcf3209ea91c1731a86e7515f4d66e
[pid: 3554|app: 0|req: 42/44] 192.168.164.4 () {38 vars in 730 bytes} [Mon Nov  5 01:27:03 2018] GET /web/zhanshi/available/0/ => generated 84902 bytes in 1603 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 8492e3c8f963868aa689cb8546902134
[pid: 3554|app: 0|req: 43/45] 192.168.164.4 () {40 vars in 796 bytes} [Mon Nov  5 01:27:10 2018] GET /web/zhanshi/available/2/ => generated 27931 bytes in 1271 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 845dcbeed0994f3294891461931d194d
[pid: 3554|app: 0|req: 44/46] 192.168.164.4 () {38 vars in 731 bytes} [Mon Nov  5 07:42:41 2018] GET /web/zhanshi/available/0/ => generated 84902 bytes in 1447 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
xxx 13d1fc2068ad890aa82f3af3461b407b
[pid: 3554|app: 0|req: 45/47] 192.168.164.4 () {40 vars in 797 bytes} [Mon Nov  5 07:42:44 2018] GET /web/zhanshi/available/2/ => generated 27931 bytes in 902 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
[pid: 3554|app: 0|req: 46/48] 192.168.164.4 () {40 vars in 785 bytes} [Mon Nov  5 07:42:47 2018] GET /web/update_hostid/ => generated 9308 bytes in 11 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
female
Internal Server Error: /web/update_hostid/
Traceback (most recent call last):
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./web/views.py", line 38, in war
    return  fun(request,*arg,**kwargs)
  File "./web/views.py", line 401, in update_hostid
    p.update_hoststatus(ip,genber)
  File "./web/zabbix_api.py", line 118, in update_hoststatus
    result = result[0]
IndexError: list index out of range
[pid: 3554|app: 0|req: 47/49] 192.168.164.4 () {48 vars in 921 bytes} [Mon Nov  5 07:47:14 2018] POST /web/update_hostid/ => generated 66678 bytes in 8341 msecs (HTTP/1.1 500) 3 headers in 106 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 3554|app: 0|req: 48/50] 192.168.164.4 () {38 vars in 684 bytes} [Mon Nov  5 07:47:22 2018] GET /favicon.ico => generated 2263 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
male
Internal Server Error: /web/update_hostid/
Traceback (most recent call last):
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./web/views.py", line 38, in war
    return  fun(request,*arg,**kwargs)
  File "./web/views.py", line 401, in update_hostid
    p.update_hoststatus(ip,genber)
  File "./web/zabbix_api.py", line 118, in update_hoststatus
    result = result[0]
IndexError: list index out of range
[pid: 3554|app: 0|req: 49/51] 192.168.164.4 () {48 vars in 919 bytes} [Mon Nov  5 07:47:47 2018] POST /web/update_hostid/ => generated 66674 bytes in 8130 msecs (HTTP/1.1 500) 3 headers in 106 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
female
Internal Server Error: /web/update_hostid/
Traceback (most recent call last):
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./web/views.py", line 38, in war
    return  fun(request,*arg,**kwargs)
  File "./web/views.py", line 401, in update_hostid
    p.update_hoststatus(ip,genber)
  File "./web/zabbix_api.py", line 118, in update_hoststatus
    result = result[0]
IndexError: list index out of range
[pid: 3554|app: 0|req: 50/52] 192.168.164.4 () {48 vars in 921 bytes} [Mon Nov  5 07:54:37 2018] POST /web/update_hostid/ => generated 66644 bytes in 8757 msecs (HTTP/1.1 500) 3 headers in 106 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
male
Internal Server Error: /web/update_hostid/
Traceback (most recent call last):
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python27/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./web/views.py", line 38, in war
    return  fun(request,*arg,**kwargs)
  File "./web/views.py", line 401, in update_hostid
    p.update_hoststatus(ip,genber)
  File "./web/zabbix_api.py", line 118, in update_hoststatus
    result = result[0]
IndexError: list index out of range
[pid: 3554|app: 0|req: 51/53] 192.168.164.4 () {48 vars in 921 bytes} [Mon Nov  5 07:54:59 2018] POST /web/update_hostid/ => generated 66642 bytes in 7704 msecs (HTTP/1.1 500) 3 headers in 106 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
female
[pid: 3554|app: 0|req: 52/54] 192.168.164.4 () {48 vars in 921 bytes} [Mon Nov  5 07:56:12 2018] POST /web/update_hostid/ => generated 9331 bytes in 64768 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
female
[pid: 3554|app: 0|req: 53/55] 192.168.164.4 () {48 vars in 921 bytes} [Mon Nov  5 07:57:18 2018] POST /web/update_hostid/ => generated 9331 bytes in 68879 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 3554|app: -1|req: -1/56] 192.168.164.4 () {38 vars in 704 bytes} [Mon Nov  5 07:58:33 2018] GET /static/favicon.ico => generated 32988 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 3 headers in 128 bytes (0 switches on core 0)
{u'user': u'hantao'}
===============
[pid: 3554|app: 0|req: 54/57] 192.168.164.4 () {40 vars in 785 bytes} [Mon Nov  5 07:58:36 2018] GET /web/update_hostid/ => generated 9308 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{u'user': u'hantao'}
===============
female
[pid: 3554|app: 0|req: 55/58] 192.168.164.4 () {48 vars in 920 bytes} [Mon Nov  5 07:59:13 2018] POST /web/update_hostid/ => generated 9331 bytes in 60160 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
